In [1]:
import pandas as pd
from preprocess.inputoutput import Reader
import numpy as np
import preprocess.datacleaning as dc

In [2]:
reader = Reader()
df_1 = reader.read_in('./datasets/AppGallery.csv')
df_2 = reader.read_in('./datasets/Purchasing.csv')

In [3]:
df_1 = dc.rename_headers(df_1)
df_1 = dc.drop_unnamed_cols(df_1)

df_2 = dc.rename_headers(df_2)
df_2 = dc.drop_unnamed_cols(df_2)

In [4]:
merged = dc.merge_dfs([df_1, df_2])
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 206 entries, 0 to 83
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ticket_id               206 non-null    int64
 1   interaction_id          206 non-null    int64
 2   interaction_date        169 non-null    float64
 3   mailbox                 206 non-null    object
 4   ticket_summary          197 non-null    object
 5   interaction_content     204 non-null    object
 6   innso_typology_ticket_  206 non-null    object
 7   type_1                  206 non-null    object
 8   type_2                  206 non-null    object
 9   type_3                  171 non-null    object
 10  type_4                  163 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 19.3+ KB

In [5]:
df_1[df_1['interaction_content'].isna()]

,ticket_id,interaction_id,interaction_date,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
63,22964,64204,44805.38125,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
65,22964,64204,NaN,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN

In [6]:
na_handler = dc.NaHandler(["interaction_content", "ticket_summary"])

df = na_handler.drop_na_rows(merged)
df.head(100000)

,ticket_id,interaction_id,interaction_date,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,24310,68365,NaN,support.eu@aspiegel.com,[HUAWEI Music] Problems and Suggestions,Mxxxxx@xxxx.com Отправлено с моего телефона Hu...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
1,24075,67730,NaN,support.pt@aspiegel.com,[AppGallery]Probleme und Vorschläge,Beschreibung Update lässt sich nicht installie...,AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Problem/Fault,AppGallery-Install/Upgrade,Can't update Apps
2,24075,67762,NaN,support.pt@aspiegel.com,Re: RE : [AppGallery]Probleme und Vorschläge R...,Danke Nach Neuinstallation der App funktionier...,AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Problem/Fault,AppGallery-Install/Upgrade,Can't update Apps
3,23748,66706,NaN,support.pt@aspiegel.com,[AppGallery]Problems and suggestions,Description . Contact information Axxxxx@xxxx.com,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Suggestion,AppGallery-Use,Others
5,23683,66429,NaN,support.eu@aspiegel.com,Aspiegel Support issue submit,Product: AppGallery & Games Requests: Using Ap...,AppGallery &amp; Games / Information request ...,AppGallery &amp; Games,Suggestion,VIP / Offers / Promotions,Offers / Vouchers / Promotions
...,...,...,...,...,...,...,...,...,...,...,...
79,22578,64275,44805.46944,support.it@Company.com,RE : Pagamenti,"Gentile *****(PER), Grazie per la vostra pazie...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
80,22576,64283,44805.48125,support.it@Company.com,RE : Rimborso,"Gentile *****(PER), Grazie per la vostra pazie...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
81,22576,64449,44805.68611,support.it@Company.com,Re: RE : Rimborso,"Gentile *****(PER), la ringrazio per il lavoro...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
82,22576,64455,44805.69236,support.it@Company.com,RE : Rimborso,"Gentile *****(PER), La ringraziamo per averci ...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
83,22508,64520,44805.81319,support.eu@Company.com,RE : Company Support issue submit,"Dear Customer, I would like to follow up on th...",In-App Purchase / Cancel /terminate subscription,In-App Purchase,Suggestion,Payment,Subscription cancellation

In [7]:
df = dc.drop_useless_cols(df)
df.head(10000)

,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,support.eu@aspiegel.com,[HUAWEI Music] Problems and Suggestions,Mxxxxx@xxxx.com Отправлено с моего телефона Hu...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
1,support.pt@aspiegel.com,[AppGallery]Probleme und Vorschläge,Beschreibung Update lässt sich nicht installie...,AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Problem/Fault,AppGallery-Install/Upgrade,Can't update Apps
2,support.pt@aspiegel.com,Re: RE : [AppGallery]Probleme und Vorschläge R...,Danke Nach Neuinstallation der App funktionier...,AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Problem/Fault,AppGallery-Install/Upgrade,Can't update Apps
3,support.pt@aspiegel.com,[AppGallery]Problems and suggestions,Description . Contact information Axxxxx@xxxx.com,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Suggestion,AppGallery-Use,Others
5,support.eu@aspiegel.com,Aspiegel Support issue submit,Product: AppGallery & Games Requests: Using Ap...,AppGallery &amp; Games / Information request ...,AppGallery &amp; Games,Suggestion,VIP / Offers / Promotions,Offers / Vouchers / Promotions
...,...,...,...,...,...,...,...,...
79,support.it@Company.com,RE : Pagamenti,"Gentile *****(PER), Grazie per la vostra pazie...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
80,support.it@Company.com,RE : Rimborso,"Gentile *****(PER), Grazie per la vostra pazie...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
81,support.it@Company.com,Re: RE : Rimborso,"Gentile *****(PER), la ringrazio per il lavoro...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
82,support.it@Company.com,RE : Rimborso,"Gentile *****(PER), La ringraziamo per averci ...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
83,support.eu@Company.com,RE : Company Support issue submit,"Dear Customer, I would like to follow up on th...",In-App Purchase / Cancel /terminate subscription,In-App Purchase,Suggestion,Payment,Subscription cancellation

In [8]:
from Harrys_fetaure_engineering import feature_engineering as fe

fe.process_data(df)

one_hot:                     mailbox  \
0   support.eu@aspiegel.com
1   support.pt@aspiegel.com
2   support.pt@aspiegel.com
3   support.pt@aspiegel.com
5   support.eu@aspiegel.com
..                      ...
79   support.it@Company.com
80   support.it@Company.com
81   support.it@Company.com
82   support.it@Company.com
83   support.eu@Company.com

                                       ticket_summary  \
0             [HUAWEI Music] Problems and Suggestions
1                 [AppGallery]Probleme und Vorschläge
2   Re: RE : [AppGallery]Probleme und Vorschläge R...
3                [AppGallery]Problems and suggestions
5                       Aspiegel Support issue submit
..                                                ...
79                                     RE : Pagamenti
80                                      RE : Rimborso
81                                  Re: RE : Rimborso
82                                      RE : Rimborso
83                  RE : Company Support issue submit

                                  interaction_content  \
0   Mxxxxx@xxxx.com Отправлено с моего телефона Hu...
1   Beschreibung Update lässt sich nicht installie...
2   Danke Nach Neuinstallation der App funktionier...
3   Description . Contact information Axxxxx@xxxx.com
5   Product: AppGallery & Games Requests: Using Ap...
..                                                ...
79  Gentile *****(PER), Grazie per la vostra pazie...
80  Gentile *****(PER), Grazie per la vostra pazie...
81  Gentile *****(PER), la ringrazio per il lavoro...
82  Gentile *****(PER), La ringraziamo per averci ...
83  Dear Customer, I would like to follow up on th...

                               innso_typology_ticket_  \
0             AppGallery &amp; Games / Other Requests
1   AppGallery &amp; Games / Suggestions &amp; Fee...
2   AppGallery &amp; Games / Suggestions &amp; Fee...
3             AppGallery &amp; Games / Other Requests
5   AppGallery &amp; Games /  Information request ...
..                                                ...
79  In-App Purchase / Unauthorised charges- bank a...
80  In-App Purchase / Unauthorised charges- bank a...
81  In-App Purchase / Unauthorised charges- bank a...
82  In-App Purchase / Unauthorised charges- bank a...
83   In-App Purchase / Cancel /terminate subscription

                     type_1         type_2                      type_3  \
0   AppGallery &amp; Games          Others                         NaN
1   AppGallery &amp; Games   Problem/Fault  AppGallery-Install/Upgrade
2   AppGallery &amp; Games   Problem/Fault  AppGallery-Install/Upgrade
3   AppGallery &amp; Games      Suggestion              AppGallery-Use
5   AppGallery &amp; Games      Suggestion   VIP / Offers / Promotions
..                      ...            ...                         ...
79         In-App Purchase   Problem/Fault               Payment issue
80         In-App Purchase   Problem/Fault               Payment issue
81         In-App Purchase   Problem/Fault               Payment issue
82         In-App Purchase   Problem/Fault               Payment issue
83         In-App Purchase      Suggestion                     Payment

                            type_4
0                              NaN
1                Can't update Apps
2                Can't update Apps
3                           Others
5   Offers / Vouchers / Promotions
..                             ...
79                    Risk Control
80                    Risk Control
81                    Risk Control
82                    Risk Control
83       Subscription cancellation

[195 rows x 8 columns]
label_encode:                     mailbox  \
0   support.eu@aspiegel.com
1   support.pt@aspiegel.com
2   support.pt@aspiegel.com
3   support.pt@aspiegel.com
5   support.eu@aspiegel.com
..                      ...
79   support.it@Company.com
80   support.it@Company.com
81   support.it@Company.com
82   support.it@Company.com
83   support.eu@Company.com

                                       ticket_summary  \
0             [HUAWEI Music] Problems and Suggestions
1                 [AppGallery]Probleme und Vorschläge
2   Re: RE : [AppGallery]Probleme und Vorschläge R...
3                [AppGallery]Problems and suggestions
5                       Aspiegel Support issue submit
..                                                ...
79                                     RE : Pagamenti
80                                      RE : Rimborso
81                                  Re: RE : Rimborso
82                                      RE : Rimborso
83                  RE : Company Support issue submit

                                  interaction_content  \
0   Mxxxxx@xxxx.com Отправлено с моего телефона Hu...
1   Beschreibung Update lässt sich nicht installie...
2   Danke Nach Neuinstallation der App funktionier...
3   Description . Contact information Axxxxx@xxxx.com
5   Product: AppGallery & Games Requests: Using Ap...
..                                                ...
79  Gentile *****(PER), Grazie per la vostra pazie...
80  Gentile *****(PER), Grazie per la vostra pazie...
81  Gentile *****(PER), la ringrazio per il lavoro...
82  Gentile *****(PER), La ringraziamo per averci ...
83  Dear Customer, I would like to follow up on th...

                               innso_typology_ticket_  \
0             AppGallery &amp; Games / Other Requests
1   AppGallery &amp; Games / Suggestions &amp; Fee...
2   AppGallery &amp; Games / Suggestions &amp; Fee...
3             AppGallery &amp; Games / Other Requests
5   AppGallery &amp; Games /  Information request ...
..                                                ...
79  In-App Purchase / Unauthorised charges- bank a...
80  In-App Purchase / Unauthorised charges- bank a...
81  In-App Purchase / Unauthorised charges- bank a...
82  In-App Purchase / Unauthorised charges- bank a...
83   In-App Purchase / Cancel /terminate subscription

                     type_1         type_2                      type_3  \
0   AppGallery &amp; Games          Others                         NaN
1   AppGallery &amp; Games   Problem/Fault  AppGallery-Install/Upgrade
2   AppGallery &amp; Games   Problem/Fault  AppGallery-Install/Upgrade
3   AppGallery &amp; Games      Suggestion              AppGallery-Use
5   AppGallery &amp; Games      Suggestion   VIP / Offers / Promotions
..                      ...            ...                         ...
79         In-App Purchase   Problem/Fault               Payment issue
80         In-App Purchase   Problem/Fault               Payment issue
81         In-App Purchase   Problem/Fault               Payment issue
82         In-App Purchase   Problem/Fault               Payment issue
83         In-App Purchase      Suggestion                     Payment

                            type_4
0                              NaN
1                Can't update Apps
2                Can't update Apps
3                           Others
5   Offers / Vouchers / Promotions
..                             ...
79                    Risk Control
80                    Risk Control
81                    Risk Control
82                    Risk Control
83       Subscription cancellation

[195 rows x 8 columns]
word_embeddings:                     mailbox  \
0   support.eu@aspiegel.com
1   support.pt@aspiegel.com
2   support.pt@aspiegel.com
3   support.pt@aspiegel.com
5   support.eu@aspiegel.com
..                      ...
79   support.it@Company.com
80   support.it@Company.com
81   support.it@Company.com
82   support.it@Company.com
83   support.eu@Company.com

                                       ticket_summary  \
0             [HUAWEI Music] Problems and Suggestions
1                 [AppGallery]Probleme und Vorschläge
2   Re: RE : [AppGallery]Probleme und Vorschläge R...
3                [AppGallery]Problems and suggestions
5                       Aspiegel Support issue submit
..                                                ...
79                                     RE : Pagamenti
80                                      RE : Rimborso
81                                  Re: RE : Rimborso
82                                      RE : Rimborso
83                  RE : Company Support issue submit

                                  interaction_content  \
0   Mxxxxx@xxxx.com Отправлено с моего телефона Hu...
1   Beschreibung Update lässt sich nicht installie...
2   Danke Nach Neuinstallation der App funktionier...
3   Description . Contact information Axxxxx@xxxx.com
5   Product: AppGallery & Games Requests: Using Ap...
..                                                ...
79  Gentile *****(PER), Grazie per la vostra pazie...
80  Gentile *****(PER), Grazie per la vostra pazie...
81  Gentile *****(PER), la ringrazio per il lavoro...
82  Gentile *****(PER), La ringraziamo per averci ...
83  Dear Customer, I would like to follow up on th...

                               innso_typology_ticket_  \
0             AppGallery &amp; Games / Other Requests
1   AppGallery &amp; Games / Suggestions &amp; Fee...
2   AppGallery &amp; Games / Suggestions &amp; Fee...
3             AppGallery &amp; Games / Other Requests
5   AppGallery &amp; Games /  Information request ...
..                                                ...
79  In-App Purchase / Unauthorised charges- bank a...
80  In-App Purchase / Unauthorised charges- bank a...
81  In-App Purchase / Unauthorised charges- bank a...
82  In-App Purchase / Unauthorised charges- bank a...
83   In-App Purchase / Cancel /terminate subscription

                     type_1         type_2                      type_3  \
0   AppGallery &amp; Games          Others                         NaN
1   AppGallery &amp; Games   Problem/Fault  AppGallery-Install/Upgrade
2   AppGallery &amp; Games   Problem/Fault  AppGallery-Install/Upgrade
3   AppGallery &amp; Games      Suggestion              AppGallery-Use
5   AppGallery &amp; Games      Suggestion   VIP / Offers / Promotions
..                      ...            ...                         ...
79         In-App Purchase   Problem/Fault               Payment issue
80         In-App Purchase   Problem/Fault               Payment issue
81         In-App Purchase   Problem/Fault               Payment issue
82         In-App Purchase   Problem/Fault               Payment issue
83         In-App Purchase      Suggestion                     Payment

                            type_4
0                              NaN
1                Can't update Apps
2                Can't update Apps
3                           Others
5   Offers / Vouchers / Promotions
..                             ...
79                    Risk Control
80                    Risk Control
81                    Risk Control
82                    Risk Control
83       Subscription cancellation

[195 rows x 8 columns]